# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node_version: ['12']
        os: [windows-latest ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
        
      - name: Run cmd to install npm
        run: npm install -g tfx-cli
        
      - name: Change the Version Number of the Widget & create VSIX file
        shell: pwsh 
        run: |
          $json = Get-Content "vss-extension.json" | ConvertFrom-Json
          $json.version = "1.0.${{ github.run_number }}"
          $json = $json | ConvertTo-Json -Depth 10
          Set-Content vss-extension.json -Value $json
        env: 
          PATCH: GITHUB_RUN_NUMBER
          
          
      - name: Write the Secret PAT
        shell: pwsh
        run: |
          $html = (Get-Content "hello-world.html") -replace 'PLACEHOLDER', '${{secrets.PAT_DEVOPS}}'
          Set-Content "testWidgetHTML.html" -Value $html

      - name: VS Marketplace Publisher
        shell: pwsh
        run: |
          tfx extension publish --manifest-globs vss-extension.json --share-with planb-germany --token ${{secrets.PAT}}
